# The name of the site
site_name: TNT Wizards Wiki

# What theme the site is using
theme:
  name: material

# Place extensions here, see https://squidfunk.github.io/mkdocs-material/reference/
markdown_extentions:
  - tables
  - meta
